### PR TITLE
Refactor QuickStep to use a single data array

### PR DESCRIPTION
**Pull request by ppiastucki**
This PR ports changes from ODE to make QuickStep use just a single array of doubles to store all coefficients for LCP solver.

**Implementation:**
The patch contains introduction of some simple abstraction for Info2Descr in order to keep the existing Step implementation intact and changes to QuickStep to use new Info2DescrQuickStep that holds all data in a single array. This changes are based directly on the respective code in ODE.
**Testing & Results:**
It looks like there is a bug in the current QuickStep implementation that manifests itself when running DemoFeedback. I have not investigated it too deeply, but it seems this PR fixes the issue. Here are some videos showing the problem
1) Reference simulation generated with ODE - https://vimeo.com/182307000
2) Current QuickStep in ode4j - https://vimeo.com/182307103
3) After applying this patch - https://vimeo.com/182307183

There is a small but measurable performance improvement, between 2.5% and 5% depending on the scene complexity.

Finally, I know all these static values do not look great, but that is the way it is done in ODE.

### CODE REVIEW

**Comment by tzaeschke** [comment]
Excellent!
The many static values indeed don't look good, but my policy was always to stay close to ODE where possible, to simplify migrating future updates.

DemoFeedback used to work earlier, but it must have broken at some point. 

What is weird is that with your patch, my DemoFeedback actually breaks in the middle, rather than at the ends (Windows 10, Intel 47xx, Java 1.6.0_45 64bit):

demofeedbackcapture

**Comment by ppiastucki** [comment]
Hi,
I used a kind of "slow motion" when I captured the videos by setting the number of step (nrofsteps) to 1 regardless of the actual framerate. It looks like it impacts the result in both ODE and ode4j.  
Here is a video at the proper speed generated with ODE, looks similar to what ode4j outputs and what you got: https://vimeo.com/182563995.
Also, ODE must be switched to double precision as single precision yields different results. What is also worth investigating is the way this demo runs when quickStep is replaced with step - the result is completely different.

**Comment by tzaeschke** [comment]
Okay, that seems to explain it. There is still a small difference though, my stack of boxes is falling to the right, yours to the left. Also, yours is ripping between the 6/7 and 7/8 element (counted from left) mine is ripping first only between 7/8 and then much later between 8/9...
I'm not sure we need to follow this up, it's probably down to different settings in the DemoFeedback. But if you like me to record a video, could you recommend a recorder? It tried OBS, but it only produces stills for me...

**Comment by ppiastucki** [comment]
Please keep in mind that the previous video was render with ODE. 
Here is another one rendered with ode4j on my machine - https://vimeo.com/182719234. 
The result seems to be very close to what you get. I think the differences between ODE and ode4j in this case might be caused by different optimizations applied by C++ compilers and JVM JIT compiler. For instance, multiplications replaced by additions etc. that result in slightly different floating-point errors that accumulate over time. I remember once I built ODE on a Linux machine and on a Mac with exactly the same flags yet the results yielded by them were slightly different. Again, I would say xcode on Mac and gcc on Linux optimized the code differently when it comes to floating-point operations. BTW, I used Kazam on Linux to record these screencasts.

**Comment by tzaeschke** [comment]
Ah sorry, I didn't see it was done with ODE. Yes there are differences between ODE and ode4j. Apparently even Java itself can be [inconsistent between versions](http://stackoverflow.com/questions/33870711/java-math-expdouble-vs-strictmath-expdouble). StrictMath may help a bit but it's probably not worth it because of the additional cost.

**Pull request merged**
