### PR TITLE
Add support for convex-trimesh collisions

### PR DESCRIPTION
**Pull request by piotr-piastucki**
Hi,

The patch adds support for convex vs trimesh coliision detection. It uses libCCD and gimpact to do a convex - triangle check for all potentially colliding triangles. Additionally some contact perturbation is applied as described in https://bullet.googlecode.com/files/GDC10_Coumans_Erwin_Contact.pdf when only a single contact is found to improve the stability.
The respective patch has also been submitted to ODE and merged in https://bitbucket.org/odedevs/ode/commits/79c1ae08892b12bf6f8ac89040d4f1f89cd57ee0

### CODE REVIEW

**Comment by tzaeschke** [comment]
Great, thanks for the patch.
I noticed that the new convex/trimesh collision appears to often create 'jitter', i.e. bodies keep wiggling around, for example if you simply drop 6 or so Convexes in DemoTrimesh. Have you noticed that?

**Comment by piotr-piastucki** [comment]
Yes. I believe the instability in convex collisions is caused by the way GJK algorithm works. It always reports a single contact and this is generally fine for round-shaped, sphere-like convex hulls, but fails for cube-like shapes with large flat surfaces. It is nicely described in the presentation I mentioned before -  https://bullet.googlecode.com/files/GDC10_Coumans_Erwin_Contact.pdf. 
In case of DemoTrimesh we have probably the worst-case scenario as the trimesh consists of large triangles collides with large convex cubes.
For convex - trimesh collisions I applied some contact perturbation as described in the above-mentioned presentation and it seems to improve the stability significantly. For instance, please see what happens to the 3rd cube in DemoTrimesh with and without perturbation when contact visualization is turned on. You can change the value of CONTACT_PERTURBATION_ANGLE in the CollisionLibccd class to 0 to see the difference. Without perturbations only a single contact is reported which is a different vertex of the cube in each frame leading to the cube slowly sliding down the triangle. With perturbations 3 contact are reported making the cube stay in place.

However, the problem affects also other collisions that use libCCD and GJK i.e. convex vs convex, convex vs sphere etc. As soon as a convex shape collides with another convex shape you will run into the same stability problems due to a single contact being reported at a time. I think this is the cause of the jitter you noticed. As long as the shapes are round enough a single contact will do, but for cubes it is most likely not enough.
The same approach with contact perturbation should be probably applied to other collision detection methods based on libCCD but this looks like a separate improvement :)
If you feel there is still something wrong with the convex-trimesh collisions unrelated to potential instability in collisions with other shapes please let me know and I will try to investigate further.

**Comment by tzaeschke** [comment]
Thanks. Do you think we should put that in the Wiki, maybe on a Tips&Tricks page? I created a page here: https://github.com/tzaeschke/ode4j/wiki/Tips-and-Tricks
It is based on your text (I hope that's okay), but I adapted a bit to make it sound more wiki-ish. Please feel free to edit it.

**Comment by piotr-piastucki** [comment]
It looks good. I think it might be useful to collect such information in one place so that people encountering known problems can easily find it.

**Pull request merged**
