### PR TITLE
Modularize take 2

### PR DESCRIPTION
**Pull request by io7m**
Attempt to modularize the project (again!)
    
This is another attempt to modularize the project. This version
should provide better support for building the code on older
compilers (Android in particular).
    
It works by adding a profile named "on-jdk-9-plus" that is activated
when the building JDK is >= JDK 9. This profile adds Java 9-specific
source directories named src/main/java9 to each module containing
a module descriptor. The profile also upgrades SLF4J to a Java 9
compatible version.
    
It also adds other JDKs to the Travis CI configuration to test that
the project builds on all of them.

### CODE REVIEW

**Comment by io7m** [comment]
The downside to this approach is that you'll get a different result depending on whether you build on JDK >= 9 compared to JDK < 9. This means that if you release to Maven Central, you need to remember to do the build on JDK 9.

@jfelrod1960 I'd appreciate it if you could try building this one to make sure it works on your system (and the Android tools)!

**Comment by jfelrod1960** [comment]
@io7m Give me until the end of this week to try this.  I'm in a Groovy/Grails class all of this week.

**Comment by tzaeschke** [comment]
@jfelrod1960 Let us know how it work for you. I'm also busy (this and next week), but I try to give it a go myself.

**Comment by io7m** [comment]
@jfelrod1960 You'll be happy to know that the performance of Java on the desktop with an Oracle/OpenJDK/IBM JDK is a hell of a lot better than that of the sorry excuse for a runtime on Android. :grin:

**Comment by jfelrod1960** [comment]
@io7m TBH Mark you may want to go to Java 10.  Java 11 is schedule to come out in September of this year and Oracle is promising long time support of both Java 8 and Java 11.  Java 10 is not getting long time support, but you can take advantage of some of the changes in Java 10 now which includes Java 9 modules.  Just a thought.

**Comment by io7m** [comment]
Yep!

I'm actually probably going to be skipping 10 and going straight to 11. The problem for me right now is that there's no JDK 9 or 10 for FreeBSD, but porting efforts are going to be targeted at 11 specifically because it has long term support.

**Comment by tzaeschke** [comment]
That's actually pretty cool! I wasn't aware that maven can do this. Thanks!

**Pull request merged**
