### PR TITLE
Refactor space geom access to use iterators

### PR DESCRIPTION
**Pull request by ppiastucki**
Hi,

This is a pure refactoring PR - an attempt to clean up the way geoms are stored within a space. 
It completely removes the custom linked list (_next, _prev fields in DxGeom), changes the collection in DxSpace from ArrayList to LinkedList for performance reasons (adding an element to ArrayList at index0 requires the whole array to be shifted) and replaces getGeom() with getGeoms() to provide access to geoms within a space.
Obviously the changes affect the API and they are not backward compatible, but I do not think retrieving particular geoms from space by index is something users of ode4j really use anyway.

This commit includes the following changes:
- change _geoms collection from ArrayList to LinkedList
- remove getGeom() from DxSpace and add getGeoms() to DxSpace instead
- remove fields that are no longer used from DxGeom and DxSpace
- add corresponding test - Test_DxSpace

Thanks,
Piotr

### CODE REVIEW

**Comment by tzaeschke** [comment]
Thanks. I like the clean-up of Demos, and I agree that the code is a bit weird. But I'm a bit reluctant to change it ...

 - The original code was a doubly-linked list where each entry knows it's predecessor and successor. This is probably the fastest and most memory-efficient way to implement it. When removing individual elements, this requires constant time O(1), while LinkedList and ArrayList rewquire linear time O(N).
 - I did some performance tests, and it appears that insert with ArrayList ist about 30% slower than with Linked List. However, iterating over the Lists takes 4-5 times longer with the LinkedList (compared to `for (int i =0; ...)`-type iteration. I didn't compare it to the original double-linked list (I ran it with '-XX:+UseConcMarkSweepGC' to avoid GC pauses, see attached file):
```
1st run
insert LinkedList: 4795
insert ArrayList: 6034
iterate LinkedList: 1948
iterate ArrayList forEach: 1376
iterate ArrayList for-i: 354

2nd run
insert LinkedList: 4710
insert ArrayList: 4851
iterate LinkedList: 1939
iterate ArrayList forEach: 1392
iterate ArrayList for-i: 379

3rd run
insert LinkedList: 3765
insert ArrayList: 5054
iterate LinkedList: 1370
iterate ArrayList forEach: 1354
iterate ArrayList for-i: 353
```

 - I also don't think we should remove API without deprecating it, simply on the assumption that nobody may use it. 

I know the current code is ugly, but I guess performance-wise this would be a step back and we would have to remove some functionality.

**Comment by ppiastucki** [comment]
Ok, I see your point. In this case I would suggest removing _geoms field from DxSpace class and use only the original implementation of doubly-linked list from ODE. It is not pretty but you are right, it is the most efficient solution performance-wise. 
Currently _geoms created as ArrayList just slow down insert/remove with very little benefit of providing faster lookup in getGeom() which IMHO is not used in real-life applications.
What do you think?  If you are OK with such a cleanup I am eager to create a new PR with the respective changes.

BTW, please do not compare iterating with for (int i =...) between ArrayList and LinkedList  as it will be much slower for LinkedList, however, iterating with Iterator should yield the same result for both kinds of list.

**Comment by ppiastucki** [comment]
Actually, I have just pushed the alternative implementation as described above so that you can review the result in this PR.

**Comment by tzaeschke** [comment]
Iterator performance: Indeed, `ArrayList` and `LinkedList` should be much the same, my point was that `for (int i=0; ...)` can be much faster. In the QuickStepper I only used this type of iteration because it's usually a performance critical area. This wouldn't have been possible with `LinkedList`.

Thanks for reworking this, looks good to me.

**Comment by ppiastucki** [comment]
Ah, ok it is clear now. Thanks for merging.
Actually, I would suggest using plain arrays instead ArrayList as much as possible in such cases, access with for (int i = 0; ...) can be usually twice as fast.

**Pull request merged**
