### PR TITLE
Simple support for rag dolls

### PR DESCRIPTION
**Pull request by piotr-piastucki**
Here is my attempt at adding generic support for rag dolls (or any other entities made of multiple bodies connected with joints). The patch adds a new type of joint - DxJointConstrainedBall, it is an extension to the regular ball and socket joint and additionally provides a way to constrain the movement as described at http://www.monsterden.net/software/ragdoll-pyode-tutorial. It is useful to implement more realistic shoulders of a human rag doll for instance.
DxRagdoll class builds the actual rag doll based on the given list of "bones" and "joints". Additionally it provides a simple autoDisable method that can be used to freeze the whole rag doll when the movement of the bodies is minimal. Usually rag doll bodies tend to oscillate due to the high number of hard constraints and disabling only some of them does not work.
Additionally, there is a demo with an example of a humanoid rag doll based on the tutorial mentioned above. The demo is extremely simple, you can only press space to apply some force.

### CODE REVIEW

**Comment by jfelrod1960** [comment]
This is great!  Thank you for the contribution!
Jeff Elrod

**Comment by tzaeschke** [comment]
Thanks, looks good.
I opened an issue (issue #24) to add Factory methods once you consider the API 'stable'. 

I saw that the Ragdoll demo complains a lot about "Zero length vector". Have you looked into that?

**Comment by tzaeschke** [comment]
Btw, I can do the factory methods, once you think it's done.

**Comment by jfelrod1960** [comment]
I don't really consider this an issue just a comment, but the ragdoll demo is throwing a "zero length vector" exception.  It is generated from a deprecated method so it is probably not an issue.  I'm going to play around with the new support for ragdolls.  Thanks!

**Comment by piotr-piastucki** [comment]
Regarding the "zero length vector" issue, it is not a real exception it is merely a debug message. I think the output is a bit confusing and probably could be less prominent. The root cause is the way the universal joint tries to re-compute its state before all the properties are set:
		DUniversalJoint joint = OdeHelper.createUniversalJoint(world);
1		joint.attach(body1.body, body2.body);
2		joint.setAnchor(anchor);
3		joint.setAxis1(axis1);
4		joint.setAxis2(axis2);

In lines 1,2,3 we face a gimbal lock and hence the warning. It should be gone when both axes are finally set in 4. The universal joint assumes some default axes but in this particular case they are really not what we want. Possibly the joint can be changed so that it will initialize itself once all the axes are set but it would change its behaviour and if someone used to rely on the default axes would need to call the setters explicitly now. Another possibility is to rework the debug message so that it will be less visible and maybe even completely silenced with a switch.

**Comment by tzaeschke** [comment]
Has anyone here used slf4j?
http://www.slf4j.org/
It seems to be pretty standard and allows interoperability with many other logging frameworks.

**Comment by piotr-piastucki** [comment]
Yes, I have been using slf4j for a while in a couple of personal and commercial projects including jTilia. I usually use it together with log4j backend (e.g. slf4j-api, slf4j-log4j12, log4j-core in pom.xml)

**Comment by tzaeschke** [comment]
I'll look into using it in ode4j then.
Btw, Logging can be disabled by setting a custom log function in the ```org.ode4j.ode.internal.ErrorHdl``` class.

**Pull request merged**
